<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\QuickPatch.Communication.Application\QuickPatch.Communication.Application.csproj" />
    <ProjectReference Include="..\QuickPatch.Communication.Infrastructure\QuickPatch.Communication.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
